set(SHADER_LIB_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ShaderLibrary CACHE INTERNAL "")
set(SHADER_LIB_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/ShaderLibrary CACHE INTERNAL "")
set(SHADER_LIB_GENERATED_DIR ${SHADER_LIB_BINARY_DIR}/generated/ CACHE INTERNAL "")
set(SHADER_LIB_SRC ${SHADER_LIB_GENERATED_DIR}/ShaderLibrary.cpp CACHE INTERNAL "")

set_source_files_properties(${SHADER_LIB_SRC} PROPERTIES GENERATED 1)
add_custom_target(GeneratedShaderLib
  DEPENDS ${SHADER_LIB_SRC}
  COMMENT "Checking if shader library re-generation is necessary")

function(GenerateShaderLib)
  add_custom_command(TARGET GeneratedShaderLib
    PRE_BUILD
    COMMAND ${CMAKE_COMMAND}
    ARGS
      "-DCMAKE_SOURCE_DIR=${SHADER_LIB_SOURCE_DIR}"
      "-DCMAKE_BINARY_DIR=${SHADER_LIB_BINARY_DIR}"
      "-DSHADERS_HEADER_FILES=${SHADERS_HEADER_FILES}"
      "-DSHADERS_STAGE_FILES=${SHADERS_STAGE_FILES}"
      "-DSHADERS_PROGRAM_FILES=${SHADERS_PROGRAM_FILES}"
      "-DSHADER_LIB_SRC=${SHADER_LIB_SRC}"
      "-DGENERATED_DIR=${SHADER_LIB_GENERATED_DIR}"
      -P ${SHADER_LIB_SOURCE_DIR}/cmake/Generate_Shaders_Lib.cmake
    VERBATIM
    COMMENT "Generating Shader Library")
  unset(SHADER_LIB_SOURCE_DIR CACHE)
  unset(SHADER_LIB_BINARY_DIR CACHE)
  unset(SHADERS_HEADER_FILES CACHE)
  unset(SHADERS_STAGE_FILES CACHE)
  unset(SHADERS_PROGRAM_FILES CACHE)
  unset(SHADER_LIB_GENERATED_DIR CACHE)
endfunction(GenerateShaderLib)