#ifndef FOG_CULLING_GLSL
#define FOG_CULLING_GLSL

#define FOG_WIDTH  128
#define FOG_HEIGHT 128
#define FOG_DEPTH  128
#define FOG_COUNT  (FOG_WIDTH * FOG_HEIGHT * FOG_DEPTH)

#endif // FOG_CULLING_GLSL