#pragma once

#include <cstdint>

namespace MSG::Keyboard {
/// @brief taken from http://www.kbdedit.com/manual/low_level_vk_list.html
enum class KeyCode : uint16_t {
    AbntC1            = 0xC1, //	Abnt C1
    AbntC2            = 0xC2, //	Abnt C2
    Add               = 0x6B, //	Numpad +
    Attn              = 0xF6, //	Attn
    Back              = 0x08, //	Backspace
    Cancel            = 0x03, //	Break
    Clear             = 0x0C, //	Clear
    Crsel             = 0xF7, //	Cr Sel
    Decimal           = 0x6E, //	Numpad .
    Divide            = 0x6F, //	Numpad /
    Ereof             = 0xF9, //	Er Eof
    Escape            = 0x1B, //	Esc
    Execute           = 0x2B, //	Execute
    Exsel             = 0xF8, //	Ex Sel
    IcoClear          = 0xE6, //	IcoClr
    IcoHelp           = 0xE3, //	IcoHlp
    Key0              = 0x30, // ('0')	0
    Key1              = 0x31, // ('1')	1
    Key2              = 0x32, // ('2')	2
    Key3              = 0x33, // ('3')	3
    Key4              = 0x34, // ('4')	4
    Key5              = 0x35, // ('5')	5
    Key6              = 0x36, // ('6')	6
    Key7              = 0x37, // ('7')	7
    Key8              = 0x38, // ('8')	8
    Key9              = 0x39, // ('9')	9
    KeyA              = 0x41, // ('A')	A
    KeyB              = 0x42, // ('B')	B
    KeyC              = 0x43, // ('C')	C
    KeyD              = 0x44, // ('D')	D
    KeyE              = 0x45, // ('E')	E
    KeyF              = 0x46, // ('F')	F
    KeyG              = 0x47, // ('G')	G
    KeyH              = 0x48, // ('H')	H
    KeyI              = 0x49, // ('I')	I
    KeyJ              = 0x4A, // ('J')	J
    KeyK              = 0x4B, // ('K')	K
    KeyL              = 0x4C, // ('L')	L
    KeyM              = 0x4D, // ('M')	M
    KeyN              = 0x4E, // ('N')	N
    KeyO              = 0x4F, // ('O')	O
    KeyP              = 0x50, // ('P')	P
    KeyQ              = 0x51, // ('Q')	Q
    KeyR              = 0x52, // ('R')	R
    KeyS              = 0x53, // ('S')	S
    KeyT              = 0x54, // ('T')	T
    KeyU              = 0x55, // ('U')	U
    KeyV              = 0x56, // ('V')	V
    KeyW              = 0x57, // ('W')	W
    KeyX              = 0x58, // ('X')	X
    KeyY              = 0x59, // ('Y')	Y
    KeyZ              = 0x5A, // ('Z')	Z
    Multiply          = 0x6A, //	Numpad *
    Noname            = 0xFC, //	NoName
    Numpad0           = 0x60, //	Numpad 0
    Numpad1           = 0x61, //	Numpad 1
    Numpad2           = 0x62, //	Numpad 2
    Numpad3           = 0x63, //	Numpad 3
    Numpad4           = 0x64, //	Numpad 4
    Numpad5           = 0x65, //	Numpad 5
    Numpad6           = 0x66, //	Numpad 6
    Numpad7           = 0x67, //	Numpad 7
    Numpad8           = 0x68, //	Numpad 8
    Numpad9           = 0x69, //	Numpad 9
    Oem1              = 0xBA, //	OEM_1 (: ;)
    Oem102            = 0xE2, //	OEM_102 (> <)
    Oem2              = 0xBF, //	OEM_2 (? /)
    Oem3              = 0xC0, //	OEM_3 (~ `)
    Oem4              = 0xDB, //	OEM_4 ({ [)
    Oem5              = 0xDC, //	OEM_5 (| \)
    Oem6              = 0xDD, //	OEM_6 (} ])
    Oem7              = 0xDE, //	OEM_7 (" ')
    Oem8              = 0xDF, //	OEM_8 (§ !)
    OemAttn           = 0xF0, //	Oem Attn
    OemAuto           = 0xF3, //	Auto
    OemAx             = 0xE1, //	Ax
    OemBacktab        = 0xF5, //	Back Tab
    OemClear          = 0xFE, //	OemClr
    OemComma          = 0xBC, //	OEM_COMMA (< ,)
    OemCopy           = 0xF2, //	Copy
    OemCusel          = 0xEF, //	Cu Sel
    OemEnlw           = 0xF4, //	Enlw
    OemFinish         = 0xF1, //	Finish
    OemFjLoya         = 0x95, //	Loya
    OemFjMasshou      = 0x93, //	Mashu
    OemFjRoya         = 0x96, //	Roya
    OemFjTouroku      = 0x94, //	Touroku
    OemJump           = 0xEA, //	Jump
    OemMinus          = 0xBD, //	OEM_MINUS (_ -)
    OemPa1            = 0xEB, //	OemPa1
    OemPa2            = 0xEC, //	OemPa2
    OemPa3            = 0xED, //	OemPa3
    OemPeriod         = 0xBE, //	OEM_PERIOD (> .)
    OemPlus           = 0xBB, //	OEM_PLUS (+ =)
    OemReset          = 0xE9, //	Reset
    OemWsctrl         = 0xEE, //	WsCtrl
    Pa1               = 0xFD, //	Pa1
    Packet            = 0xE7, //	Packet
    Play              = 0xFA, //	Play
    Processkey        = 0xE5, //	Process
    Return            = 0x0D, //	Enter
    Select            = 0x29, //	Select
    Separator         = 0x6C, //	Separator
    Space             = 0x20, //	Space
    Subtract          = 0x6D, //	Num -
    Tab               = 0x09, //	Tab
    Zoom              = 0xFB, //	Zoom Name Numeric value Description
    None              = 0xFF, //	no VK mapping
    Accept            = 0x1E, //	Accept
    Apps              = 0x5D, //	Context Menu
    BrowserBack       = 0xA6, //	Browser Back
    BrowserFavorites  = 0xAB, //	Browser Favorites
    BrowserForward    = 0xA7, //	Browser Forward
    BrowserHome       = 0xAC, //	Browser Home
    BrowserRefresh    = 0xA8, //	Browser Refresh
    BrowserSearch     = 0xAA, //	Browser Search
    BrowserStop       = 0xA9, //	Browser Stop
    Capital           = 0x14, //	Caps Lock
    Convert           = 0x1C, //	Convert
    Delete            = 0x2E, //	Delete
    Down              = 0x28, //	Arrow Down
    End               = 0x23, //	End
    F1                = 0x70, //	F1
    F10               = 0x79, //	F10
    F11               = 0x7A, //	F11
    F12               = 0x7B, //	F12
    F13               = 0x7C, //	F13
    F14               = 0x7D, //	F14
    F15               = 0x7E, //	F15
    F16               = 0x7F, //	F16
    F17               = 0x80, //	F17
    F18               = 0x81, //	F18
    F19               = 0x82, //	F19
    F2                = 0x71, //	F2
    F20               = 0x83, //	F20
    F21               = 0x84, //	F21
    F22               = 0x85, //	F22
    F23               = 0x86, //	F23
    F24               = 0x87, //	F24
    F3                = 0x72, //	F3
    F4                = 0x73, //	F4
    F5                = 0x74, //	F5
    F6                = 0x75, //	F6
    F7                = 0x76, //	F7
    F8                = 0x77, //	F8
    F9                = 0x78, //	F9
    Final             = 0x18, //	Final
    Help              = 0x2F, //	Help
    Home              = 0x24, //	Home
    Ico00             = 0xE4, //	Ico00 *
    Insert            = 0x2D, //	Insert
    Junja             = 0x17, //	Junja
    Kana              = 0x15, //	Kana
    Kanji             = 0x19, //	Kanji
    LaunchApp1        = 0xB6, //	App1
    LaunchApp2        = 0xB7, //	App2
    LaunchMail        = 0xB4, //	Mail
    LaunchMediaSelect = 0xB5, //	Media
    Lbutton           = 0x01, //	Left Button **
    Lcontrol          = 0xA2, //	Left Ctrl
    Left              = 0x25, //	Arrow Left
    Lmenu             = 0xA4, //	Left Alt
    Lshift            = 0xA0, //	Left Shift
    Lwin              = 0x5B, //	Left Win
    Mbutton           = 0x04, //	Middle Button **
    MediaNextTrack    = 0xB0, //	Next Track
    MediaPlayPause    = 0xB3, //	Play / Pause
    MediaPrevTrack    = 0xB1, //	Previous Track
    MediaStop         = 0xB2, //	Stop
    Modechange        = 0x1F, //	Mode Change
    Next              = 0x22, //	Page Down
    Nonconvert        = 0x1D, //	Non Convert
    Numlock           = 0x90, //	Num Lock
    OemFjJisho        = 0x92, //	Jisho
    Pause             = 0x13, //	Pause
    Print             = 0x2A, //	Print
    Prior             = 0x21, //	Page Up
    Rbutton           = 0x02, //	Right Button **
    Rcontrol          = 0xA3, //	Right Ctrl
    Right             = 0x27, //	Arrow Right
    Rmenu             = 0xA5, //	Right Alt
    Rshift            = 0xA1, //	Right Shift
    Rwin              = 0x5C, //	Right Win
    Scroll            = 0x91, //	Scrol Lock
    Sleep             = 0x5F, //	Sleep
    Snapshot          = 0x2C, //	Print Screen
    Up                = 0x26, //	Arrow Up
    VolumeDown        = 0xAE, //	Volume Down
    VolumeMute        = 0xAD, //	Volume Mute
    VolumeUp          = 0xAF, //	Volume Up
    Xbutton1          = 0x05, //	X Button 1 **
    Xbutton2          = 0x06, //	X Button 2 **
};
}
