include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fetch_GoogleTest.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fetch_GLM.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fetch_GLEW.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fetch_ZLib.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fetch_FasTC.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fetch_SparseHash.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fetch_SDL2.cmake)
